import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff", padding: 20, paddingTop: 60 },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  label: { fontSize: 16, marginTop: 15, marginBottom: 5 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  optionsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  option: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  optionSelected: { backgroundColor: "#4CAF50", borderColor: "#4CAF50" },
  optionText: { color: "#333" },
  optionTextSelected: { color: "#fff", fontWeight: "bold" },

  titre: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 8,
  },
  total: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  infoBanner: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D3D3D3",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginVertical: 10,
  },
  infoText: {
    color: "#856404",
    fontSize: 14,
  },
  warningBanner: {
    backgroundColor: "#FFF3CD",
    borderColor: "#FFEEBA",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginVertical: 10,
  },
  warningText: {
    color: "#856404",
    fontSize: 14,
  },
  liste: { flex: 1 },
  ligne: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  details: {
    backgroundColor: "#f5f5f5",
    padding: 10,
    borderRadius: 6,
    marginBottom: 5,
  },

  message: { textAlign: "center", marginBottom: 20, fontSize: 16 },
  macrosBox: { width: "100%", marginTop: 10 },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
  },

  editBox: { marginBottom: 15 },
  goalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  goalText: { fontSize: 16 },
  progressBarBackground: {
    height: 20,
    backgroundColor: "#eee",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 20,
  },
  progressBarFill: { height: "100%", backgroundColor: "#4CAF50" },
  statsRow: { flexDirection: "row", justifyContent: "space-around" },
  statBox: { alignItems: "center" },
  statValue: { fontSize: 20, fontWeight: "bold" },
  statLabel: { fontSize: 14, color: "#666" },

  weightInfo: {
    marginTop: 20,
    marginBottom: 10,
    fontStyle: "italic",
    color: "#666",
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    flexWrap: "wrap",
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 5,
    marginLeft: 15,
  },
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: "#fff",
    padding: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  primaryButton: {
    backgroundColor: "#0095ff",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginVertical: 8,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  card: {
    backgroundColor: "#FCFAF7",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#EFECE6",
  },
  mainTitle: {
    textAlign: "center",
    letterSpacing: 2,
    fontSize: 13,
    fontWeight: "600",
    color: "#5A524C",
    marginBottom: 8,
  },
  heroValue: {
    fontSize: 64,
    fontWeight: "bold",
    color: "#D96B27",
    textAlign: "center",
    lineHeight: 68,
  },
  unitText: {
    fontSize: 20,
    color: "#6E655F",
    textAlign: "center",
  },
  subUnitText: {
    fontSize: 14,
    color: "#8C837B",
    textAlign: "center",
    marginBottom: 16,
  },
  pillBadge: {
    backgroundColor: "#DCEBFF",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: "center",
  },
  pillBadgeText: {
    color: "#0066FF",
    fontWeight: "600",
    fontSize: 14,
  },
  gridContainer: {
    flexDirection: "row",
    gap: 10,
  },
  miniCard: {
    flex: 1,
    backgroundColor: "#FCFAF7",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#EFECE6",
    alignItems: "center",
  },
  miniCardTitle: {
    fontSize: 12,
    color: "#5A524C",
    textAlign: "center",
    marginBottom: 8,
  },
  miniCardValue: {
    fontSize: 22,
    fontWeight: "bold",
  },
  miniCardUnit: {
    fontSize: 12,
    color: "#8C837B",
  },
  miniCardSub: {
    fontSize: 11,
    color: "#8C837B",
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "serif",
    fontWeight: "bold",
    color: "#1A1A1A",
  },
  sectionSubtitle: {
    fontSize: 13,
    color: "#756D65",
    marginTop: 4,
    marginBottom: 16,
  },
  comparisonRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  comparisonBox: {
    flex: 1,
    backgroundColor: "#F2EFEB",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  compLabel: {
    fontSize: 13,
    color: "#6E655F",
    marginBottom: 4,
  },
  compValue: {
    fontSize: 22,
    fontWeight: "bold",
  },
  compUnit: {
    fontSize: 14,
    fontWeight: "normal",
  },
  greenInsightText: {
    color: "#00875A",
    fontWeight: "600",
    fontSize: 14,
    textAlign: "center",
  },
  riskAlertBox: {
    backgroundColor: "#DDF7E8",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  checkIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#A3EAD0",
    alignItems: "center",
    justifyContent: "center",
  },
  riskAlertTitle: {
    color: "#00875A",
    fontWeight: "bold",
    fontSize: 15,
    marginBottom: 2,
  },
  riskAlertDescription: {
    color: "#2C523C",
    fontSize: 13,
    lineHeight: 18,
  },
  footerNote: {
    fontSize: 12,
    color: "#5A524C",
  },
  scaleRow: {
    backgroundColor: "#F7F5F0",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  activeScaleRow: {
    backgroundColor: "#DCEBFF",
    borderWidth: 2,
    borderColor: "#0066FF",
  },
  scaleLabel: {
    fontWeight: "600",
    color: "#5A524C",
  },
  scaleValue: {
    color: "#756D65",
  },
  riskAlertBoxDanger: { backgroundColor: "#FDE2E1" },
  checkIconDanger: { backgroundColor: "#F5A3A0" },
  riskAlertTitleDanger: { color: "#C62828" },
  riskAlertDescriptionDanger: { color: "#7A2E27" },
});
